Name:           ros-indigo-backports-ssl-match-hostname
Version:        3.5.0
Release:        4%{?dist}
Summary:        ROS backports_ssl_match_hostname package

Group:          Development/Libraries
License:        Python software Foundation License
Source0:        %{name}-%{version}.tar.gz

BuildRequires:  ros-indigo-catkin >= 0.6.18
BuildRequires:  ros-indigo-catkin-pip >= 0.2.0
Conflicts:      ros-indigo-rosbridge-server <= 0.7.17

%description
The ssl.match_hostname() function from Python 3.5

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Thu Mar 23 2017 AlexV <asmodehn@gmail.com> - 3.5.0-4
- Autogenerated by Bloom

* Tue Jan 31 2017 AlexV <asmodehn@gmail.com> - 3.5.0-3
- Autogenerated by Bloom

* Thu Nov 17 2016 AlexV <asmodehn@gmail.com> - 3.5.0-2
- Autogenerated by Bloom

* Wed Nov 09 2016 Toshio Kuratomi <toshio@fedoraproject.org> - 3.5.0-1
- Autogenerated by Bloom

* Wed Nov 09 2016 Toshio Kuratomi <toshio@fedoraproject.org> - 3.5.0-0
- Autogenerated by Bloom

* Wed Nov 09 2016 Toshio Kuratomi <toshio@fedoraproject.org> - 3.4.0-0
- Autogenerated by Bloom

